//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCCycleMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CYCCycleMST()
        {
            this.CycCycleToReviewerMapIds = new HashSet<CycCycleToReviewerMapId>();
            this.CYCCycleToParameterMaps = new HashSet<CYCCycleToParameterMap>();
        }
    
        public long CYCCycleMSTId { get; set; }
        public string CycleName { get; set; }
        public Nullable<System.DateTime> CycleBeginDate { get; set; }
        public Nullable<System.DateTime> CycleEndDate { get; set; }
        public Nullable<System.DateTime> CycleReleaseReportDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CycCycleToReviewerMapId> CycCycleToReviewerMapIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CYCCycleToParameterMap> CYCCycleToParameterMaps { get; set; }
    }
}
