//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCCycleToUserMap
    {
        public long CYCCycleToUserMapId { get; set; }
        public Nullable<long> CYCCycleMSTId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Status { get; set; }
    }
}
