//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycCycleToReviewerMapId
    {
        public long CycCycleToReviewerMapId1 { get; set; }
        public long CYCCycleMSTId { get; set; }
        public long CYCReviewersMSTId { get; set; }
        public System.DateTime EvaluationDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CYCCycleMST CYCCycleMST { get; set; }
        public virtual CYCReviewersMST CYCReviewersMST { get; set; }
    }
}
