//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCParameterMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CYCParameterMST()
        {
            this.CYCQuesMSTs = new HashSet<CYCQuesMST>();
        }
    
        public long CYCParameterMSTId { get; set; }
        public string ParameterName { get; set; }
        public Nullable<long> CYCRatingSystemMSTId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CYCQuesMST> CYCQuesMSTs { get; set; }
    }
}
