//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRISEntities : DbContext
    {
        public HRISEntities()
            : base("name=HRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPActivityMst> APPActivityMsts { get; set; }
        public virtual DbSet<APPCityMst> APPCityMsts { get; set; }
        public virtual DbSet<APPContinentMst> APPContinentMsts { get; set; }
        public virtual DbSet<APPCountryMst> APPCountryMsts { get; set; }
        public virtual DbSet<APPCountyMst> APPCountyMsts { get; set; }
        public virtual DbSet<APPLocationMst> APPLocationMsts { get; set; }
        public virtual DbSet<APPStateMst> APPStateMsts { get; set; }
        public virtual DbSet<APPUserActivity> APPUserActivities { get; set; }
        public virtual DbSet<UMMForgotPassword> UMMForgotPasswords { get; set; }
        public virtual DbSet<UMMRoleMst> UMMRoleMsts { get; set; }
        public virtual DbSet<UMMUserGroup> UMMUserGroups { get; set; }
        public virtual DbSet<UMMUserGroupDetail> UMMUserGroupDetails { get; set; }
        public virtual DbSet<UMMUserLocationMap> UMMUserLocationMaps { get; set; }
        public virtual DbSet<UMMUserLogIn> UMMUserLogIns { get; set; }
        public virtual DbSet<UMMUserProfile> UMMUserProfiles { get; set; }
        public virtual DbSet<CYCCycleMST> CYCCycleMSTs { get; set; }
        public virtual DbSet<CYCCycleToParameterMap> CYCCycleToParameterMaps { get; set; }
        public virtual DbSet<CYCCycleToUserMap> CYCCycleToUserMaps { get; set; }
        public virtual DbSet<CYCEValuation> CYCEValuations { get; set; }
        public virtual DbSet<CYCGoalMST> CYCGoalMSTs { get; set; }
        public virtual DbSet<CYCParameterMST> CYCParameterMSTs { get; set; }
        public virtual DbSet<CYCQuesMST> CYCQuesMSTs { get; set; }
        public virtual DbSet<CYCRatingSystemMST> CYCRatingSystemMSTs { get; set; }
        public virtual DbSet<CYCReviewersMST> CYCReviewersMSTs { get; set; }
        public virtual DbSet<CYCSubGoalMST> CYCSubGoalMSTs { get; set; }
        public virtual DbSet<CYCSubgoalToUserMap> CYCSubgoalToUserMaps { get; set; }
        public virtual DbSet<PriorityMST> PriorityMSTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
