//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMMUserProfile
    {
        public long UMMUserProfileId { get; set; }
        public Nullable<long> APPCountryMstId { get; set; }
        public Nullable<long> AppStateMstId { get; set; }
        public Nullable<long> AppCountyMstId { get; set; }
        public Nullable<long> APPCityMstId { get; set; }
        public Nullable<long> APPZipCodeMstId { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> OMGender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Mobile { get; set; }
        public string OfficeContact { get; set; }
        public string UserEmail { get; set; }
        public string ProfileImage { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<long> OMUserType { get; set; }
        public string Expertise { get; set; }
        public string Profession { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string UserStatus { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string WorkStation { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
    }
}
